apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stockServer.name }}
  labels:
    app: {{ .Values.stockServer.name }}
spec:
  replicas: {{ .Values.stockServer.replica }}
  selector:
    matchLabels:
      app: {{ .Values.stockServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.stockServer.name }}
    spec:
      containers:
        - name: {{ .Values.stockServer.name }}
          image: {{ .Values.stockServer.image }}
          ports:
            - containerPort: {{ .Values.stockServer.port }}
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            # MySQL 관련 환경변수
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MYSQL_HOST

            # Redis 관련 환경변수
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: REDIS_URL

            # JWT 관련 환경변수
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET_KEY
            - name: JWT_ALGORITHM
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_ALGORITHM
            - name: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
            - name: JWT_REFRESH_TOKEN_EXPIRE_DAYS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_REFRESH_TOKEN_EXPIRE_DAYS

            # App key와 secret
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APP_KEY
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APP_SECRET
            - name: SSE_KEY
              valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: SSE_KEY
            - name: SSE_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: SSE_SECRET
            - name: HOGA_KEY
              valueFrom:
                secretKeyRef:
                    name: app-secret
                    key: HOGA_KEY
            - name: HOGA_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: HOGA_SECRET


