apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: stockly
  annotations:
    meta.helm.sh/release-name: "stock-server"
    meta.helm.sh/release-namespace: "stockly"
  labels:
    app.kubernetes.io/managed-by: "Helm"
type: Opaque\
data:
  # MySQL 설정
  MYSQL_ROOT_PASSWORD: c3RvY2tseQ==
  MYSQL_DATABASE: c3RvY2tseQ==
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: MTIzNDU2Nzg=
  MYSQL_HOST: bXlzcWw=
  TZ: QXNpYS9TZW91bA==

  # JWT 설정
  JWT_SECRET_KEY: MTIzNDU2Nzg5MA==
  JWT_ALGORITHM: SFMyNTY=
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: MzAwMA==
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: NQ==

  # Redis 설정
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5
  REDIS_HOST: cmVkaXM=
  REDIS_PORT: NjM3OQ==

  # 앱 키와 시크릿
  APP_KEY: UFNlbWlQWndDdW16bXBHdEpPcUl1UUdnbVUzc3ZEekloa1E3
  APP_SECRET: clhzS29oMmY1Y3k1VUVpalVqc0ExL2w3eCs5WTR5ZEJKUHdSbWxTNEMycXFvSzZrMGp3WStXQ1pPcDRtKzRzcUJhOUdkL2IzdGZFa3JMTHBKLzE3cnpXOW9SOTNkQ01xeFNkMXNXbXQyWkltb0ZTR3BSWVNOVm1DTUtZa0ltb3ZyNWU5ZDBaNEFrVlA3aStROXQ0eG1QZitHa0d0SkRUdFYzY0tZa3dLcjVqUGNCVzduSUE9
