apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stockServer.name }}
  labels:
    app: {{ .Values.stockServer.name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.stockServer.port }}
      targetPort: {{ .Values.stockServer.port }}
      protocol: TCP
      nodePort: 30080
  selector:
    app: {{ .Values.stockServer.name }}
