# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Values.stockServer.name }}
#   labels:
#     app: {{ .Values.stockServer.name }}
# spec:
#   type: ClusterIP
#   ports:
#     - port: {{ .Values.stockServer.port }}
#       targetPort: {{ .Values.stockServer.port }}
#       protocol: TCP
#   selector:
#     app: {{ .Values.stockServer.name }}


apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stockServer.name }}
  labels:
    app: {{ .Values.stockServer.name }}
spec:
  type: NodePort # NodePort로 외부 접근 허용
  ports:
    - port: {{ .Values.stockServer.port }} # 클러스터 내부 기본 포트
      targetPort: {{ .Values.stockServer.port }}
      protocol: TCP
      nodePort: 30000 # NodePort로 8000 매핑
    - port: 8000 # 추가로 8000번 포트 열기
      targetPort: {{ .Values.stockServer.port }}
      protocol: TCP
      nodePort: 30001 # NodePort로 8000번 연결
  selector:
    app: {{ .Values.stockServer.name }}
