repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: traefik
    url: https://helm.traefik.io/traefik
releases:
  - name: stock-server
    chart: ./stock-server
    namespace: stockly
    values:
      - ./stock-server/values.yaml
  - name: stock-service
    chart: ./stock-service
    namespace: stockly
    values:
      - ./stock-service/values.yaml
  - name: order-service
    chart: ./order-service
    namespace: stockly
    values:
      - ./order-service/values.yaml
  - name: mysql
    chart: ./mysql
    namespace: stockly
    values:
      - ./mysql/values.yaml
  - name: broker
    chart: ./kafka/broker
    namespace: stockly
    values:
      - ./kafka/broker/values.yaml
  - name: zookeeper
    chart: ./kafka/zookeeper
    namespace: stockly
    values:
      - ./kafka/zookeeper/values.yaml
  - name: redis
    chart: ./redis/
    namespace: stockly
    values:
      - ./redis/values.yaml
  - name: grafana
    chart: ./monitoring/grafana
    namespace: stockly
    values:
      - ./monitoring/grafana/values.yaml
  - name: loki
    chart: ./monitoring/loki
    namespace: stockly
    values:
      - ./monitoring/loki/values.yaml