repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: traefik
    url: https://helm.traefik.io/traefik
releases:
  - name: stock-server
    chart: ./stock-server
    values:
      - ./stock-server/values.yaml
  - name: stock-service
    chart: ./stock-service
    values:
      - ./stock-service/values.yaml
  - name: order-service
    chart: ./order-service
    values:
      - ./order-service/values.yaml
  - name: mypage-service
    chart: ./mypage-service
    values:
      - ./mypage-service/values.yaml
  - name: alert-service
    chart: ./alert-service
    values:
      - ./alert-service/values.yaml
  - name: mysql
    chart: ./mysql
    values:
      - ./mysql/values.yaml
  - name: kafka
    chart: ./kafka
    values:
      - ./kafka/values.yaml