# templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: localhost.kafka
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-service
                port:
                  number: {{ .Values.kafka.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zookeeper-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: localhost.zookeeper
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zookeeper-service
                port:
                  number: {{ .Values.zookeeper.port }}
