apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stock-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/StocklyProject/K3s-Infra'
    targetRevision: HEAD
    path: stock-server
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: stockly

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
