apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stockly
  name: mysql-config
data:
  init.sql: |
    SET NAMES 'utf8mb4';
    SET character_set_client = 'utf8mb4';
    SET character_set_connection = 'utf8mb4';
    SET character_set_results = 'utf8mb4';

    CREATE DATABASE IF NOT EXISTS stockly;
    USE stockly;

    -- user 테이블 생성
    CREATE TABLE IF NOT EXISTS user (
      id INT AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(100) NOT NULL,
      password VARCHAR(100) NOT NULL,
      name VARCHAR(100) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      is_deleted BOOLEAN DEFAULT FALSE
    );

    -- stock 테이블 생성
    CREATE TABLE IF NOT EXISTS stock (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_deleted TINYINT DEFAULT 0,
    symbol VARCHAR(100),
    high INT,
    low INT,
    volume BIGINT,
    date DATETIME,
    open INT,
    close INT,
    rate DOUBLE,
    rate_price INT,
    trading_value BIGINT,
    is_daily BOOLEAN DEFAULT TRUE
    );

    -- companies 테이블 생성
    CREATE TABLE IF NOT EXISTS company (
      id INT AUTO_INCREMENT PRIMARY KEY,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      is_deleted TINYINT(1) DEFAULT 0,
      name VARCHAR(100) NOT NULL,
      symbol VARCHAR(100) NOT NULL
    );

    -- companies 초기 데이터 삽입
    INSERT INTO company (name, symbol) VALUES
      ('삼성전자', '005930'),
      ('LG', '003550'),
      ('SK하이닉스', '000660'),
      ('삼성바이오로직스','207940'),
      ('기아', '000270');

      
  my.cnf: |
    [ client ]
    default-character-set = utf8mb4

    [ mysql ]
    default-character-set = utf8mb4

    [ mysqld ]
    character-set-client-handshake = FALSE
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    init-connect='SET NAMES utf8mb4'