apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stockly
  name: mysql-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS stockly;
    USE stockly;
    CREATE TABLE IF NOT EXISTS user (
      id INT AUTO_INCREMENT PRIMARY KEY,
      email VARCHAR(100) NOT NULL,
      password VARCHAR(100) NOT NULL,
      name VARCHAR(100) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      is_deleted BOOLEAN DEFAULT FALSE
    );
