apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: stockly
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c3RvY2tseQ==
  MYSQL_DATABASE: c3RvY2tseQ==
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: MTIzNDU2Nzg=
  MYSQL_HOST: bXlzcWw=