apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      nodePort: 30079 # 고정 NodePort (30000~32767 범위)
  selector:
    app: redis
