apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: {{ .Values.replicaCount }}  # 브로커 수 설정
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # 이미지 설정
          ports:
            - name: client
              containerPort: {{ .Values.listeners.client.containerPort }}  # 클라이언트 포트
            - name: external
              containerPort: {{ .Values.listeners.external.containerPort }}  # 외부 포트
            - name: interbroker
              containerPort: {{ .Values.listeners.interbroker.containerPort }}  # 브로커 간 포트
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zoo-headless.stockly.svc.cluster.local:2181"  # Zookeeper 연결 설정
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094"  # 리스너 설정
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-{{ .Values.replicaIndex }}.stockly.svc.cluster.local:9092,EXTERNAL://localhost:9094"  # 광고 리스너 설정
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"  # 보안 프로토콜 설정
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"  # PLAINTEXT 리스너 허용
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}  # 메모리 제한
              cpu: {{ .Values.resources.limits.cpu }}  # CPU 제한
            requests:
              memory: {{ .Values.resources.requests.memory }}  # 메모리 요청
              cpu: {{ .Values.resources.requests.cpu }}  # CPU 요청
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka/data  # 데이터 저장 경로
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi  # 원하는 스토리지 크기로 조정