apiVersion: v2
name: order-service
description: A Helm chart for the Stockly project, which includes order-service

version: 1.0.0
appVersion: "1.0.0"

keywords:
  - stock
  - investment
  - trading
  - kafka
  - microservices