apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.ports.web.port }}
      name: web
    - port: {{ .Values.ports.websecure.port }}
      name: websecure
    - port: {{ .Values.ports.dashboard.port }}
      name: dashboard
      targetPort: 9000
      protocol: TCP
  selector:
    app: traefik
