apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api.insecure=true" # 개발 용이성을 위한 insecure 통신 가능 설정
      - "--api.dashboard=true" # 대시보드 활성화
      - "--log.level=DEBUG"  # 로그 레벨을 DEBUG로 설정

    ports:
      web:
        expose: true
        port: 80
        exposedPort: 80
      websecure:
        expose: true
        port: 443
        exposedPort: 443
      traefik:
        expose: true
        port: 9000
        exposedPort: 9000

    providers:
      kubernetesCRD:
        allowCrossNamespace: true # 다른 네임스페이스의 Ingress 리소스 허용

    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: mlb-address-pool-1 # 필요한 경우 MetalLB 설정
