apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.script.configMapName }}
data:
  {{ .Values.script.fileName }}: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    export let options = {
      vus: {{ .Values.job.vus }},
      duration: '{{ .Values.job.testDuration }}',
    };

    export default function () {
      http.get('http://example.com');
      sleep(1);
    }
