apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script-config
  namespace: stockly
data:
  test.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
      vus: 10,
      duration: '1m',
    };

    export default function () {
      let res = http.get('http://localhost:30080/docs');
      check(res, { 'status was 200': (r) => r.status === 200 });

      const lokiUrl = __ENV.LOKI_URL; // Loki URL 환경 변수
      const payload = JSON.stringify({
        streams: [
          {
            stream: { app: 'k6' },
            values: [
              [String(new Date().getTime() * 1e6), `Response time: ${res.timings.duration}ms`],
            ],
          },
        ],
      });

      const headers = { 'Content-Type': 'application/json' };

      const lokiResponse = http.post(lokiUrl, payload, { headers });
      check(lokiResponse, { 'Loki push successful': (r) => r.status === 204 });

      sleep(1);
    }
