apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-k6-job
  labels:
    app: k6
spec:
  parallelism: {{ .Values.job.parallelism }}
  template:
    metadata:
      labels:
        app: k6
    spec:
      containers:
        - name: k6
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - k6
            - run
            - /scripts/{{ .Values.script.fileName }}
          env:
            - name: LOKI_URL
              value: "{{ .Values.loki.url }}"
          volumeMounts:
            - name: k6-scripts
              mountPath: /scripts
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Never
      volumes:
        - name: k6-scripts
          configMap:
            name: {{ .Values.script.configMapName }}
