apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-k6-job
  labels:
    app: k6
spec:
  parallelism: {{ .Values.job.parallelism }}
  template:
    metadata:
      labels:
        app: k6
    spec:
      containers:
        - name: k6
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              k6 run --out loki={{ .Values.loki.url }} /scripts/{{ .Values.script.fileName }}
          env:
            {{- if .Values.env }}
            {{- range .Values.env }}
            - name: "{{ .name }}"
              value: "{{ .value }}"
            {{- end }}
            {{- end }}
          volumeMounts:
            - name: k6-scripts
              mountPath: /scripts
              readOnly: true  # ConfigMap은 읽기 전용
      restartPolicy: Never
      volumes:
        - name: k6-scripts
          configMap:
            name: {{ .Values.script.configMapName }}
