apiVersion: v1
kind: Secret
metadata:
  name: order-secret
  namespace: stockly
  annotations:
    meta.helm.sh/release-name: "order-service"
    meta.helm.sh/release-namespace: "stockly"
  labels:
    app.kubernetes.io/managed-by: "Helm"
type: Opaque\
data:
  # MySQL 설정
  MYSQL_ROOT_PASSWORD: c3RvY2tseQ==
  MYSQL_DATABASE: c3RvY2tseQ==
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: MTIzNDU2Nzg=
  MYSQL_HOST: bXlzcWw=
  TZ: QXNpYS9TZW91bA==
