apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-loki-config
  labels:
    app: loki
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
      {{- toYaml .Values.config.schema_config.configs | nindent 8 }}
    storage_config:
      {{- toYaml .Values.config.storage_config | nindent 6 }}
