apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-loki
  labels:
    app: loki
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
        - name: init-loki-directories
          image: busybox
          command: ["sh", "-c", "mkdir -p /data/loki/boltdb-shipper-active /data/loki/boltdb-shipper-cache /data/loki/chunks /data/loki/wal && chmod -R 777 /data/loki"]
          volumeMounts:
            - name: loki-data
              mountPath: /data/loki
      containers:
        - name: loki
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          args:
            - -config.file=/etc/loki/loki-config.yaml
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
            - name: loki-data
              mountPath: /data/loki
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: loki-config
          configMap:
            name: {{ .Release.Name }}-loki-config

        - name: loki-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-loki-pvc
