apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stockService.name }}
  labels:
    app: {{ .Values.stockService.name }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.stockService.port }}
      targetPort: {{ .Values.stockService.port }}
      protocol: TCP
      nodePort: 30081 # 30000~32767 만 사용 가능
  selector:
    app: {{ .Values.stockService.name }}

