mysql:
  name: mysql
  replica: 1
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/mysql
    tag: 8.0.32-debian-11-r0  # 원하는 버전으로 수정 가능
  service:
    port: 3306
  auth:
    secretName: mysql-secret
  primary:
    persistence:
      enabled: true
      size: 8Gi  # 원하는 크기로 수정