mysql:
  name: mysql
  replica: 1
  enabled: true
  image: mysql:latest
  service:
    port: 3306
  auth:
    secretName: mysql-secret
configmaps:
  mysqlInitdbConfigName: mysql-config
pvc:
  enabled: true
  name: mysql-pvc
  storage: 10Gi