apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: "kafka-headless"
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          ports:
            - containerPort: {{ .Values.kafka.ports.clientPort }}
              name: client
            - containerPort: {{ .Values.kafka.ports.externalPort }}
              name: external
          env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ .Values.kafka.zookeeperConnect }}