apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: {{ .Values.kafkaUI.image }}
          ports:
            - containerPort: {{ .Values.kafkaUI.service.port }}
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: {{ .Values.kafkaUI.env.KAFKA_CLUSTERS_0_NAME }}
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: {{ .Values.kafkaUI.env.KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS }}
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: {{ .Values.kafkaUI.env.KAFKA_CLUSTERS_0_ZOOKEEPER }}
            - name: KAFKA_CLUSTERS_0_READONLY
              value: {{ .Values.kafkaUI.env.KAFKA_CLUSTERS_0_READONLY }}