apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: "kafka-headless"
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: {{ .Values.kafka.image }}
          ports:
            - containerPort: {{ .Values.kafka.ports.clientPort }}
              name: client
            - containerPort: {{ .Values.kafka.ports.externalPort }}
              name: external
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          command:
            - sh
            - -c
            - |
              export KAFKA_BROKER_ID=$(echo ${HOSTNAME} | awk -F'-' '{print $NF}')
              export KAFKA_ZOOKEEPER_CONNECT="zookeeper-headless:2181"
              export KAFKA_CFG_LISTENERS="PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094"
              export KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://${HOSTNAME}.kafka-headless:9092,EXTERNAL://localhost:9094"
              export KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP="PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
              exec kafka-server-start.sh /opt/bitnami/kafka/config/server.properties
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.kafka.persistence.size }}