apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
spec:
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: election
    - port: 3888
      name: leader
  clusterIP: None
  selector:
    app: zookeeper