replicaCount: 3

kafka:
  image: "bitnami/kafka:2.8.0"
  port: 9092
  resources:
    limits:
      memory: "1Gi"
      cpu: "1000m"
    requests:
      memory: "512Mi"
      cpu: "500m"

zookeeper:
  enabled: true
  image: "bitnami/zookeeper:3.7.0"
  port: 2181
  resources:
    limits:
      memory: "1Gi"
      cpu: "1000m"
    requests:
      memory: "512Mi"
      cpu: "500m"
