apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: {{ .Values.replicaCount }}  # Zookeeper 인스턴스 수
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image }}  # 이미지 설정
          ports:
            - name: client
              containerPort: {{ .Values.zookeeper.port }}  # 포트 설정
          resources:
            limits:
              memory: {{ .Values.zookeeper.resources.limits.memory }}
              cpu: {{ .Values.zookeeper.resources.limits.cpu }}
            requests:
              memory: {{ .Values.zookeeper.resources.requests.memory }}
              cpu: {{ .Values.zookeeper.resources.requests.cpu }}
          volumeMounts:
            - name: zookeeper-data
              mountPath: /bitnami/zookeeper/data  # 데이터 저장 경로
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"  # 익명 로그인 허용
            - name: ZOO_ENABLE_AUTH
              value: "false"  # 인증 비활성화
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi  # 원하는 스토리지 크기로 조정