name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test_and_push:
    name: k3s-infra CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create output
        run: sh ./build.sh

      - name: Set timezone to Asia/Seoul
        run: echo "TZ='Asia/Seoul'" >> /etc/environment

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUSH_TOKEN }}
        with:
          source-directory: 'output'
          destination-github-username: 'Stockly-Project'
          destination-repository-name: 'K3s-Infra'
          user-email: ${{ secrets.EMAIL }}
          commit-message: |
            ${{ github.event.head_commit.message || 'feat: update repository (' }}$(date +'%m:%d')${{ ')' }}
          target-branch: 'main'

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
